export const systemDocumentation = {
  title: 'Overseas Employment Agency Worker & Invoice Management System',
  architecture: {
    pattern: 'SplitDeploy (Express REST APIs + React Vite + MySQL)',
    layers: [
      {
        name: 'Frontend Layer',
        tech: 'React 19, TypeScript, Tailwind CSS v4, Lucide Icons, Recharts',
        role: 'Responsive Burmese/English UI, Dashboard metrics, Worker & Deployment management, Billing tracker, PDF/Excel export',
      },
      {
        name: 'Backend API Layer',
        tech: 'Node.js, Express, layered routes/controllers/services',
        role: 'RESTful endpoints, automated invoice date calculation, outstanding balance computation, Gemini AI integration',
      },
      {
        name: 'Data Storage Layer',
        tech: 'MySQL 8.0',
        role: 'Normalized storage for workers, deployments, financial configurations, invoices',
      },
    ],
  },
  databaseSchema: {
    tables: [
      {
        tableName: 'users',
        description: 'Login accounts (plain-text password match)',
        columns: [
          { name: 'id', type: 'VARCHAR(36)', key: 'PK', desc: 'User ID' },
          { name: 'name', type: 'VARCHAR(100)', key: 'NOT NULL', desc: 'Display name' },
          { name: 'email', type: 'VARCHAR(150)', key: 'UNIQUE', desc: 'Login email' },
          { name: 'password', type: 'VARCHAR(255)', key: 'NOT NULL', desc: 'Plain text password' },
          {
            name: 'role',
            type: "ENUM('Admin', 'Manager', 'Staff')",
            key: 'NOT NULL',
            desc: 'Access role',
          },
          { name: 'title', type: 'VARCHAR(150)', key: 'NULLABLE', desc: 'Job title' },
          { name: 'is_active', type: 'TINYINT(1)', key: 'DEFAULT 1', desc: 'Active flag' },
        ],
      },
      {
        tableName: 'workers',
        description: 'Core worker profile and current operational status',
        columns: [
          { name: 'id', type: 'VARCHAR(36)', key: 'PK', desc: 'Unique worker identifier' },
          { name: 'serial_no', type: 'VARCHAR(20)', key: 'UNIQUE', desc: 'Agency Serial ID' },
          { name: 'name', type: 'VARCHAR(100)', key: 'NOT NULL', desc: 'Worker full name' },
          { name: 'gender', type: "ENUM('Male', 'Female')", key: 'NOT NULL', desc: 'Gender' },
          { name: 'dob', type: 'DATE', key: 'NOT NULL', desc: 'Date of Birth' },
          { name: 'passport_no', type: 'VARCHAR(30)', key: 'NOT NULL', desc: 'Passport Number' },
          {
            name: 'status',
            type: "ENUM('Active', 'Contract Ended', 'Absconded')",
            key: 'NOT NULL',
            desc: 'Current employment status',
          },
          { name: 'absconded_date', type: 'DATE', key: 'NULLABLE', desc: 'Absconded date' },
          { name: 'notes', type: 'TEXT', key: 'NULLABLE', desc: 'Remarks' },
        ],
      },
      {
        tableName: 'deployments',
        description: 'Visa, Supervising Organization, and Host Company',
        columns: [
          { name: 'id', type: 'VARCHAR(36)', key: 'PK', desc: 'Deployment ID' },
          { name: 'worker_id', type: 'VARCHAR(36)', key: 'FK -> workers.id', desc: 'Worker FK' },
          { name: 'visa_type', type: 'VARCHAR(50)', key: 'NOT NULL', desc: 'Visa type' },
          { name: 'supervising_org', type: 'VARCHAR(150)', key: 'NOT NULL', desc: 'Supervising Org' },
          { name: 'host_company', type: 'VARCHAR(150)', key: 'NOT NULL', desc: 'Host Company' },
          { name: 'job_category', type: 'VARCHAR(100)', key: 'NOT NULL', desc: 'Job category' },
          { name: 'own_card_date', type: 'DATE', key: 'NULLABLE', desc: 'Own Card Date' },
          { name: 'departure_date', type: 'DATE', key: 'NULLABLE', desc: 'Departure Date' },
          { name: 'japan_entry_date', type: 'DATE', key: 'NULLABLE', desc: 'Japan Entry Date' },
          { name: 'contract_end_date', type: 'DATE', key: 'NULLABLE', desc: 'Contract End Date' },
        ],
      },
      {
        tableName: 'financial_configs',
        description: 'Fee structure per worker',
        columns: [
          { name: 'id', type: 'VARCHAR(36)', key: 'PK', desc: 'Config ID' },
          { name: 'worker_id', type: 'VARCHAR(36)', key: 'FK -> workers.id', desc: 'Worker FK' },
          { name: 'flight_fee', type: 'DECIMAL(12,2)', key: 'DEFAULT 0', desc: 'Flight fee' },
          { name: 'training_fee', type: 'DECIMAL(12,2)', key: 'DEFAULT 0', desc: 'Training fee' },
          { name: 'management_fee', type: 'DECIMAL(12,2)', key: 'NOT NULL', desc: 'Management fee' },
          { name: 'billing_cycle_months', type: 'INT', key: 'DEFAULT 6', desc: 'Billing cycle' },
        ],
      },
      {
        tableName: 'invoices',
        description: 'Billing history and outstanding balances',
        columns: [
          { name: 'id', type: 'VARCHAR(36)', key: 'PK', desc: 'Invoice ID' },
          { name: 'invoice_no', type: 'VARCHAR(30)', key: 'UNIQUE', desc: 'Invoice Number' },
          { name: 'worker_id', type: 'VARCHAR(36)', key: 'FK -> workers.id', desc: 'Worker FK' },
          {
            name: 'fee_type',
            type: "ENUM('management','flight','training')",
            key: 'NOT NULL',
            desc: 'Fee category',
          },
          { name: 'billing_period', type: 'VARCHAR(50)', key: 'NOT NULL', desc: 'Billing period' },
          { name: 'last_invoice_date', type: 'DATE', key: 'NOT NULL', desc: 'Last invoice date' },
          { name: 'next_invoice_date', type: 'DATE', key: 'NOT NULL', desc: 'Next invoice date' },
          { name: 'total_amount', type: 'DECIMAL(12,2)', key: 'NOT NULL', desc: 'Total amount' },
          { name: 'amount_received', type: 'DECIMAL(12,2)', key: 'DEFAULT 0', desc: 'Received' },
          { name: 'outstanding_amount', type: 'DECIMAL(12,2)', key: 'COMPUTED', desc: 'Outstanding' },
          { name: 'payment_received_date', type: 'DATE', key: 'NULLABLE', desc: 'Payment date' },
          { name: 'receipt_no', type: 'VARCHAR(50)', key: 'NULLABLE', desc: 'Receipt No' },
          { name: 'receipt_sent_date', type: 'DATE', key: 'NULLABLE', desc: 'Receipt sent date' },
          {
            name: 'status',
            type: "ENUM('Pending', 'Partial', 'Paid', 'Overdue')",
            key: 'NOT NULL',
            desc: 'Status',
          },
          { name: 'currency', type: "ENUM('JPY','MMK','USD')", key: 'NOT NULL', desc: 'Currency' },
        ],
      },
      {
        tableName: 'fee_payments',
        description: 'Legacy — payments now recorded via invoices.fee_type',
        columns: [
          { name: 'id', type: 'VARCHAR(64)', key: 'PK', desc: 'Payment ID' },
          { name: 'worker_id', type: 'VARCHAR(64)', key: 'FK -> workers.id', desc: 'Worker FK' },
          {
            name: 'fee_type',
            type: "ENUM('flight','training')",
            key: 'NOT NULL',
            desc: 'Fee type',
          },
          { name: 'amount', type: 'DECIMAL(12,2)', key: 'NOT NULL', desc: 'Amount' },
          { name: 'payment_date', type: 'DATE', key: 'NOT NULL', desc: 'Payment date' },
        ],
      },
    ],
  },
  systemFlow: [
    '1. Worker Registration -> Profile + financial config amounts (flight / training / management fees).',
    '2. Deployment Lifecycle -> Visa, host company, departure / Japan entry; contract end monitored for expiry alerts.',
    '3. Invoicing -> Create invoice by fee type; record full or installment payment (amount received) on the invoice.',
    '4. Alerts -> Management fee next-invoice date within 7 days; contracts ending within 30 days.',
    '5. Reports -> Upcoming management invoices, outstanding balances, flight/training status from invoices, contract expirations.',
  ],
};
