import React, { createContext, useContext, useMemo, useState, useCallback } from 'react';
import { JP } from '../i18n/jp';

export type Lang = 'MM' | 'EN' | 'JP';

type Dict = Record<string, string>;

const MM: Dict = {
  'nav.dashboard': 'ပင်မ ဒက်ရှ်ဘုတ်',
  'nav.workers': 'အလုပ်သမား',
  'nav.students': 'ကျောင်းသား',
  'nav.deployments': 'ဗီဇာ / စာချုပ်',
  'nav.invoices': 'ငွေစာရင်း',
  'nav.reports': 'အစီရင်ခံစာ',
  'nav.settings': 'ဆက်တင်',
  'nav.menu': 'လမ်းညွှန် မီနူး',
  'nav.systemStatus': 'စနစ် အခြေအနေ',
  'nav.logout': 'ထွက်မည်',
  'nav.notifications': 'အသိပေးချက်များ',
  'nav.tagline': 'ပြည်ပအလုပ်အကိုင်အေဂျင်စီနှင့် ငွေစာရင်း စီမံခန့်ခွဲမှု',

  'alert.title': 'အဓိက သတိပေးချက်များ',
  'alert.subtitle': 'ရှေ့လာမည့် ငွေတောင်းခံလွှာနှင့် စာချုပ်သက်တမ်းကုန်မည့်စာရင်းများကို ဤနေရာတွင် စစ်ဆေးပါ',
  'alert.urgentInvoices': 'ရှေ့ ၇ ရက်အတွင်း ငွေတောင်းခံလွှာ ထုတ်ရန်',
  'alert.expiring': 'စာချုပ် သက်တမ်း ကုန်တော့မည့်သူများ',
  'alert.none': 'သတိပေးချက် မရှိပါ',
  'alert.countInvoices': 'ခု',
  'alert.countWorkers': 'ဦး',
  'alert.filterAll': 'အားလုံး',
  'alert.totalBadge': 'ခု',
  'alert.colType': 'အမျိုးအစား',
  'alert.colSubject': 'အမည် / နံပါတ်',
  'alert.colDetail': 'Host Company',
  'alert.colDate': 'ရက်စွဲ',
  'alert.goInvoices': 'ငွေစာရင်းသို့',
  'alert.goDeployments': 'Deployment သို့',
  'alert.markAllRead': 'အားလုံး ဖတ်ပြီးဟု မှတ်မည်',
  'alert.unreadBadge': 'ခု မဖတ်ရသေး',
  'alert.enableBrowser': 'Browser Notification ဖွင့်မည်',
  'alert.browserOn': 'Browser Notification ဖွင့်ထားသည်',
  'alert.browserDenied': 'Browser တွင် ငြင်းပယ်ထားသည်',
  'alert.browserUnsupported': 'ဤ Browser သည် Notification မပံ့ပိုးပါ။',
  'alert.testPush': 'Test Push ပို့မည်',
  'alert.vapidMissing': 'backend/.env တွင် VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY ထည့်ရန် လိုပါသည်။',
  'alert.pushReady': 'Web Push ချိတ်ဆက်ပြီးပါပြီ။',
  'alert.pushError': 'Web Push ချိတ်ဆက်၍ မရပါ။ Browser permission / VAPID keys ကို စစ်ပါ။',

  'common.loading': 'စနစ် ဒေတာများ ရယူနေပါသည်...',
  'common.search': 'ရှာရန်...',
  'common.allStatuses': 'အခြေအနေ အားလုံး',
  'common.actions': 'လုပ်ဆောင်ချက်',
  'common.status': 'အခြေအနေ',
  'common.cancel': 'မလုပ်တော့ပါ',
  'common.save': 'သိမ်းဆည်းမည်',
  'common.delete': 'ဖျက်ရန်',
  'common.edit': 'ပြင်ဆင်ရန်',
  'common.close': 'ပိတ်မည်',
  'common.select': '— ရွေးပါ —',
  'common.male': 'ကျား',
  'common.female': 'မ',
  'common.noData': 'မှတ်တမ်း မရှိသေးပါ',
  'common.online': 'အွန်လိုင်း',
  'common.showFilters': 'Search / Filter ပြရန်',
  'common.hideFilters': 'Search / Filter ပိတ်ရန်',

  'print.copy': 'Copy',
  'print.copySuccess': 'Clipboard သို့ ကူးပြီးပါပြီ',
  'print.copySuccessHint': 'Chat / Messenger ထဲတွင် Paste လုပ်၍ ပုံအဖြစ် ပို့နိုင်ပါသည်။',
  'print.shareSuccess': 'Share အောင်မြင်ပါသည်',
  'print.downloadSuccess': 'ပုံ ဒေါင်းလုဒ် လုပ်ပြီးပါပြီ',
  'print.downloadSuccessHint': 'Download ဖိုင်ကို Chat ထဲသို့ ပို့နိုင်ပါသည်။',
  'print.copyFail': 'Copy မရပါ',

  'export.excel': 'Excel Export',
  'export.pdf': 'PDF ဒေါင်းလုဒ်',

  'pagination.rowsPerPage': 'စာမျက်နှာအလိုက် အတန်း',
  'pagination.showing': 'ပြသနေသည်',
  'pagination.of': 'မှ',
  'pagination.previous': 'နောက်သို့',
  'pagination.next': 'ရှေ့သို့',
  'pagination.page': 'စာမျက်နှာ',

  'login.title': 'အသုံးပြုသူ ဝင်ရောက်ရန်',
  'login.welcome': 'အကောင့်ဖြင့် ဆက်လက် အသုံးပြုနိုင်ပါသည်။',
  'login.heroLine': 'Overseas employment operations, billing & contracts — one workspace.',
  'login.email': 'အီးမေးလ်',
  'login.password': 'စကားဝှက်',
  'login.remember': 'အကောင့်မှတ်ထားမည်',
  'login.submit': 'ဝင်ရောက်မည်',
  'login.loggingIn': 'ဝင်ရောက်နေပါသည်...',
  'login.needFields': 'ကျေးဇူးပြု၍ အီးမေးလ်နှင့် စကားဝှက် ဖြည့်သွင်းပါ။',
  'login.invalid': 'အီးမေးလ် သို့မဟုတ် စကားဝှက် မှားနေပါသည်',
  'login.failed': 'ဝင်ရောက်မှု မအောင်မြင်ပါ။',
  'login.serverError': 'ဆာဗာနှင့် ချိတ်ဆက်၍ မရပါ။',
  'login.showPassword': 'စကားဝှက် ပြရန်',
  'login.hidePassword': 'စကားဝှက် ဖျောက်ရန်',

  'workers.title': 'အလုပ်သမား ကိုယ်ရေးအချက်အလက် စီမံခန့်ခွဲခြင်း',
  'students.title': 'ကျောင်းသား ကိုယ်ရေးအချက်အလက် စီမံခန့်ခွဲခြင်း',
  'students.subtitle': 'မိတ်ဆက်ကြေး၊ ပေးချေမှုနှင့် voucher မှတ်တမ်းများ',
  'students.add': 'ကျောင်းသားသစ် သွင်းရန်',
  'students.search': 'အမည်၊ စဉ်၊ Passport၊ ကျောင်းအမည်ဖြင့် ရှာရန်...',
  'students.empty': 'ကျောင်းသား မှတ်တမ်း မရှိပါ။',
  'students.createTitle': 'ကျောင်းသားသစ် စာရင်းသွင်းရန်',
  'students.editTitle': 'ကျောင်းသား အချက်အလက် ပြင်ဆင်ရန်',
  'students.createHint': 'မိတ်ဆက်ကြေးသာ သတ်မှတ်ပါ။ ပေးချေမှုကို Fee စာမျက်နှာတွင် မှတ်ပါ။',
  'students.editHint': 'ကျောင်းသား profile နှင့် မိတ်ဆက်ကြေး ပြင်ဆင်ရန်',
  'students.sectionProfile': '၁။ ကျောင်းသား ကိုယ်ရေးအချက်အလက်',
  'students.sectionDeployment': '၂။ ဗီဇာနှင့် ကျောင်း အချက်အလက်များ',
  'students.sectionFinancial': '၃။ မိတ်ဆက်ကြေး (Introduction Fee)',
  'students.financialHint': 'Introduction Fee ကို JPY ဖြင့် သတ်မှတ်သည်။ ပေးချေမှု / voucher ကို Introduction Fees စာမျက်နှာတွင် မှတ်ပါ။',
  'students.introductionFee': 'မိတ်ဆက်ကြေး',
  'students.incompleteTitle': 'အချက်အလက် မပြည့်စုံပါ',
  'students.nameRequired': 'ကျောင်းသား အမည် ထည့်သွင်းပါ။',
  'students.dropdownRequired': 'Visa / ကျောင်းအမည် / ကျောင်းလိပ်စာ ဖြည့်ပါ။',
  'students.fieldsRequired': 'Visa / ကျောင်းအမည် / ကျောင်းလိပ်စာ ဖြည့်ပါ။',
  'students.visaHint': 'Visa နှင့် ကျောင်းအမည်ကို Settings → System Variables မှ ရွေးချယ်ပါ။',
  'students.schoolInvoiceHint': 'School Name ရွေးပြီး ထိုကျောင်းအောက်ရှိ ကျောင်းသားများ၏ Introduction Fee စုစုပေါင်းဖြင့် Invoice ထုတ်ပါ။',
  'students.schoolInvoiceAmountHint': 'ပမာဏသည် ကျောင်းသားများ၏ Introduction Fee စုစုပေါင်းဖြစ်သည် (ပြင်ဆင်နိုင်သည်)။',
  'students.schoolStudents': 'ဤကျောင်းအောက်ရှိ ကျောင်းသားများ',
  'students.schoolStudentsEmpty': 'ဤ School Name အောက်တွင် ကျောင်းသား မရှိသေးပါ။',
  'students.studentCount': 'ကျောင်းသားဦးရေ',
  'students.searchSchool': 'School Name ဖြင့် ရှာရန်...',
  'students.schoolName': 'ကျောင်းအမည်',
  'students.schoolAddress': 'ကျောင်းလိပ်စာ',
  'students.colSchool': 'ကျောင်းအမည် / လိပ်စာ',
  'students.openFees': 'Introduction Fee',
  'students.profilesTab': 'Profiles',
  'students.feesTab': 'Introduction Fees',
  'students.feesTitle': 'ကျောင်းသား မိတ်ဆက်ကြေး စီမံခန့်ခွဲမှု',
  'students.feesSubtitle': 'Invoice ထုတ်ခြင်း၊ ပေးချေမှုနှင့် voucher',
  'students.feesEmpty': 'ဤ Introduction Fee အတွက် မှတ်တမ်း မရှိပါ။',
  'students.deleteTitle': 'ကျောင်းသား ဖျက်မည်?',
  'students.deleteSimple': 'ဤကျောင်းသား ({name}) စာရင်းကို စနစ်မှ အပြီးတိုင် ဖျက်မည်။',
  'students.deleteRelatedTitle': 'ဆက်စပ် Student Invoice ရှိနေပါသည်',
  'students.deleteRelatedText': '{name} ({serial}) နှင့် သက်ဆိုင်သော Student Invoice မှတ်တမ်း {count} ခု ရှိနေပါသည်။ Hard Delete လုပ်ပါက ဆက်စပ်မှတ်တမ်းများကိုပါ ဖျက်ပါမည်။',
  'students.deleteRelatedList': 'ဆက်စပ် Student Invoice များ',
  'students.deleteConfirmSimple': 'ဖျက်မည်',
  'students.deleteConfirmHard': 'Hard Delete',
  'students.deleteCancel': 'မလုပ်တော့ပါ',
  'students.deleted': 'ကျောင်းသား ဖျက်ပြီးပါပြီ',
  'students.deletedWithRelated': 'ကျောင်းသားနှင့် ဆက်စပ် Invoice {count} ခုကို ဖျက်ပြီးပါပြီ',
  'students.deleteFail': 'ဖျက်၍ မရပါ',
  'students.deleteLoadFail': 'ဆက်စပ် မှတ်တမ်း စစ်ဆေး၍ မရပါ',
  'students.deleteInvoiceTitle': 'Student invoice ဖျက်မည်?',
  'students.deleteInvoiceText': 'ဤ student introduction invoice ကို ဖျက်ရန် သေချာပါသလား?',
  'students.deleteInvoiceSuccess': 'Student invoice ဖျက်ပြီးပါပြီ',
  'students.deleteInvoiceFail': 'Student invoice ဖျက်၍ မရပါ',
  'students.invoiceHint': 'ပေးချေမှုကို Pay ခလုတ်ဖြင့် သီးခြား မှတ်ပါ',
  'deployments.title': 'ဗီဇာ / စာချုပ် စီမံခန့်ခွဲခြင်း',
  'deployments.subtitle': 'ဗီဇာ၊ ကုမ္ပဏီ၊ ထွက်ခွာ/Japan Entry ရက်နှင့် စာချုပ်သက်တမ်း စောင့်ကြည့်ရန်',
  'workers.subtitle': 'ကိုယ်ရေးအချက်အလက်၊ အခြေအနေ (Active / Absconded / Ended) နှင့် မှတ်ချက်များ',
  'workers.add': 'အလုပ်သမားသစ် သွင်းရန်',
  'workers.template': 'Excel Template',
  'workers.import': 'Excel Import',
  'workers.importSuccess': 'အလုပ်သမား {count} ဦးကို Excel မှ သွင်းပြီးပါပြီ',
  'workers.importFailTitle': 'Excel Import မအောင်မြင်ပါ',
  'workers.importFailHint': 'Settings နှင့် မကိုက်ညီသောကြောင့် data insert မလုပ်ဘဲ rollback လုပ်ထားပါသည်။',
  'workers.importing': 'Import လုပ်နေသည်...',
  'workers.search': 'အမည်၊ စဉ်၊ နိုင်ငံကူးလက်မှတ်၊ မှတ်ချက်ဖြင့် ရှာရန်...',
  'deployments.search': 'အမည်၊ Passport၊ Host Company၊ Visa ဖြင့် ရှာရန်...',
  'workers.allVisas': 'ဗီဇာ အမျိုးအစား အားလုံး',
  'workers.colName': 'စဉ် / အမည်',
  'workers.colPassport': 'နိုင်ငံကူးလက်မှတ် / မွေးသက္ကရာဇ်',
  'workers.colVisa': 'ဗီဇာ / အလုပ်အမျိုးအစား',
  'workers.colCompany': 'ကြီးကြပ်ရေး / လက်ခံကုမ္ပဏီ',
  'workers.colHostBrief': 'လက်ခံကုမ္ပဏီ',
  'workers.colContract': 'စာချုပ်ပြီးဆုံးရက်',
  'workers.departure': 'ထွက်ခွာ',
  'workers.empty': 'ရှာဖွေမှုနှင့် ကိုက်ညီသော အလုပ်သမား မရှိပါ။',
  'deployments.empty': 'ရှာဖွေမှုနှင့် ကိုက်ညီသော ဗီဇာ/စာချုပ် မှတ်တမ်း မရှိပါ။',
  'deployments.colVisa': 'ဗီဇာ / အလုပ်အမျိုးအစား',
  'deployments.colCompany': 'လက်ခံကုမ္ပဏီ / ကြီးကြပ်ရေး',
  'deployments.colOwnCard': 'Own Card',
  'deployments.colDeparture': 'ထွက်ခွာရက်',
  'deployments.colJapanEntry': 'Japan Entry',
  'deployments.colContract': 'စာချုပ်ပြီးဆုံးရက်',
  'deployments.allExpiry': 'စာချုပ်သက်တမ်း အားလုံး',
  'deployments.expiry30': '၃၀ ရက်အတွင်း ကုန်မည်',
  'deployments.expiry90': '၉၀ ရက်အတွင်း ကုန်မည်',
  'deployments.expiryPast': 'သက်တမ်းကုန်ပြီး',
  'deployments.expiryNone': 'စာချုပ်ရက် မသတ်မှတ်ရသေး',
  'deployments.daysLeft': '{days} ရက် ကျန်',
  'deployments.expiredDays': '{days} ရက် ကျော်',
  'workers.dateLabel': 'ရက်စွဲ',
  'workers.abscondedTitle': 'အလုပ်သမား ထွက်ပြေးမှု အချက်အလက် သွင်းရန်',
  'workers.abscondedConfirm': 'ထွက်ပြေးအဖြစ် အတည်ပြုမည်',
  'workers.abscondedDate': 'ထွက်ပြေးသည့် ရက်စွဲ',
  'workers.notes': 'မှတ်ချက်',
  'workers.deleteTitle': 'အလုပ်သမား ဖျက်မည်?',
  'workers.deleteSimple': 'ဤအလုပ်သမား ({name}) စာရင်းကို စနစ်မှ အပြီးတိုင် ဖျက်မည်။',
  'workers.deleteRelatedTitle': 'ဆက်စပ် Report / Invoice ရှိနေပါသည်',
  'workers.deleteRelatedText': '{name} ({serial}) နှင့် သက်ဆိုင်သော Invoice / Report မှတ်တမ်း {count} ခု ရှိနေပါသည်။ Hard Delete လုပ်ပါက ထိုဆက်စပ် မှတ်တမ်းများကိုပါ တစ်ပါတည်း ဖျက်ပါမည်။',
  'workers.deleteRelatedList': 'ဆက်စပ် Invoice များ',
  'workers.deleteConfirmSimple': 'ဖျက်မည်',
  'workers.deleteConfirmHard': 'Hard Delete (ဆက်စပ်မှတ်တမ်းပါ)',
  'workers.deleteCancel': 'မလုပ်တော့ပါ',
  'workers.deleted': 'အလုပ်သမား ဖျက်ပြီးပါပြီ',
  'workers.deletedWithRelated': 'အလုပ်သမားနှင့် ဆက်စပ် Invoice {count} ခုကို ဖျက်ပြီးပါပြီ',
  'workers.deleteFail': 'ဖျက်၍ မရပါ',
  'workers.deleteLoadFail': 'ဆက်စပ် မှတ်တမ်း စစ်ဆေး၍ မရပါ',

  'workerModal.addTitle': 'အလုပ်သမားသစ် စာရင်းသွင်းရန်',
  'workerModal.editTitle': 'အလုပ်သမား အချက်အလက် ပြင်ဆင်ရန်',
  'workerModal.createHint': 'အလုပ်သမားအသစ်၏ ကိုယ်ရေး၊ ဗီဇာနှင့် ကြေးနှုန်းများကို ဖြည့်သွင်းပါ။',
  'workerModal.editHint': 'အလုပ်သမား အချက်အလက်များကို ပြင်ဆင်ပြီး သိမ်းဆည်းပါ။',
  'workerModal.incompleteTitle': 'အချက်အလက် မပြည့်စုံပါ',
  'workerModal.financialHint':
    'ဤနေရာတွင် Fee Amount သတ်မှတ်ရုံသာ။ ပေးချေမှုမှတ်တမ်းကို Invoice စာမျက်နှာတွင် လုပ်ဆောင်ပါ။',
  'workerModal.section1': '၁။ အလုပ်သမား ကိုယ်ရေးအချက်အလက်',
  'workerModal.section2': '၂။ ဗီဇာနှင့် စာချုပ် အချက်အလက်များ',
  'workerModal.section3': '၃။ ငွေကြေး / ကြေးနှုန်းများ',
  'workerModal.serial': 'စဉ် နံပါတ်',
  'workerModal.name': 'အမည် *',
  'workerModal.gender': 'ကျား/မ',
  'workerModal.dob': 'မွေးသက္ကရာဇ်',
  'workerModal.passport': 'နိုင်ငံကူးလက်မှတ် နံပါတ် *',
  'workerModal.status': 'အခြေအနေ',
  'workerModal.abscondedDate': 'ထွက်ပြေးသည့် ရက်စွဲ',
  'workerModal.visa': 'ဗီဇာ အမျိုးအစား *',
  'workerModal.org': 'ကြီးကြပ်ရေးအဖွဲ့ *',
  'workerModal.host': 'လက်ခံ ကုမ္ပဏီ *',
  'workerModal.job': 'အလုပ်အမျိုးအစား *',
  'workerModal.ownCard': 'ကိုယ်ပိုင်ကတ် ရရှိသည့်နေ့',
  'workerModal.departure': 'ထွက်ခွာသည့်နေ့',
  'workerModal.entry': 'ဂျပန် ဝင်သည့်နေ့',
  'workerModal.contractEnd': 'စာချုပ်ပြီးဆုံးရက်',
  'workerModal.dropdownHint': 'ဗီဇာ / အဖွဲ့ / ကုမ္ပဏီ / အလုပ်တို့ကို ဆက်တင်ရှိ စနစ်ကိန်းရှင်များမှ ရွေးပါ။',
  'workerModal.nameRequired': 'ကျေးဇူးပြု၍ အလုပ်သမား အမည် ထည့်သွင်းပါ။',
  'workerModal.dropdownRequired': 'ဗီဇာ / ကြီးကြပ်ရေး / ကုမ္ပဏီ / အလုပ်အမျိုးအစား ကို ရွေးချယ်ပါ။',
  'workerModal.flightFee': 'လေယာဉ်စရိတ်',
  'workerModal.trainingFee': 'သင်တန်းကြေး',
  'workerModal.managementFee': 'စီမံခန့်ခွဲမှုကြေး',
  'workerModal.billingCycle': 'ငွေတောင်းခံ ကာလ (လ)',
  'workerModal.notes': 'မှတ်ချက်',

  'workerDetail.edit': 'ပြင်ဆင်မည်',
  'workerDetail.currentStatus': 'လက်ရှိ အခြေအနေ',
  'workerDetail.personalInfo': 'ကိုယ်ရေးအချက်အလက်',
  'workerDetail.deploymentInfo': 'ဗီဇာနှင့် Deployment အသေးစိတ်',
  'workerDetail.financialInfo': 'ငွေကြေး သတ်မှတ်ချက်',
  'workerDetail.financialHint':
    'ဤနေရာတွင် Fee Amount သတ်မှတ်ရုံသာ။ ပေးချေမှုမှတ်တမ်းကို Invoice စာမျက်နှာတွင် လုပ်ဆောင်ပါ။',
  'workerDetail.invoicesTitle': 'Invoice နှင့် ပေးချေမှုမှတ်တမ်း ({count})',
  'workerDetail.noInvoices': 'ဤအလုပ်သမားအတွက် Invoice မှတ်တမ်း မထုတ်ရသေးပါ။',
  'workerDetail.passport': 'Passport',
  'workerDetail.dob': 'မွေးသက္ကရာဇ်',
  'workerDetail.close': 'ပိတ်မည်',
  'workerDetail.abscondedDate': 'ထွက်ပြေးသည့်ရက်',
  'workerDetail.billingCycle': 'Cycle: {months} လ',
  'workerDetail.notAvailable': 'N/A',
  'workerDetail.notesTitle': 'မှတ်ချက်',

  'invoices.title': 'ငွေရေးကြေးရေး နှင့် ငွေတောင်းခံလွှာ စီမံခန့်ခွဲမှု',
  'invoices.subtitle': 'စီမံခန့်ခွဲမှုကြေး ငွေတောင်းခံရမည့်ရက်၊ လက်ခံရရှိငွေ၊ ပြေစာ နှင့် ကျန်ရှိငွေများ',
  'invoices.add': 'ငွေတောင်းခံလွှာ အသစ်ထုတ်ရန်',
  'invoices.search': 'ငွေတောင်းခံလွှာ နံပါတ်၊ အလုပ်သမား၊ ကုမ္ပဏီ၊ ပြေစာဖြင့် ရှာရန်...',
  'invoices.colInvoice': 'ငွေတောင်းခံလွှာ / ကာလ',
  'invoices.colWorker': 'အလုပ်သမား / ကုမ္ပဏီ',
  'invoices.colDates': 'နောက်ဆုံး / နောက်တစ်ကြိမ် ရက်',
  'invoices.colAmount': 'ကျသင့် / ဝင်ပြီး / ကျန်ရှိငွေ',
  'invoices.colReceipt': 'ပြေစာ မှတ်တမ်း',
  'invoices.empty': 'မှတ်တမ်း မရှိသေးပါ သို့မဟုတ် ရှာဖွေမှုနှင့် မကိုက်ညီပါ။',
  'invoices.detailTitle': 'Invoice အသေးစိတ်',
  'invoices.last': 'နောက်ဆုံး',
  'invoices.next': 'နောက်တစ်ကြိမ်',
  'invoices.total': 'ကျသင့်',
  'invoices.received': 'ဝင်ပြီး',
  'invoices.outstanding': 'ကျန်',
  'invoices.totalAmount': 'စုစုပေါင်း ကျသင့်',
  'invoices.totalPaid': 'စုစုပေါင်း ပေးပြီး',
  'invoices.remainAmount': 'ကျန်ငွေ',
  'invoices.invoiceCount': 'Invoice အရေအတွက်',
  'invoices.searchWorker': 'အလုပ်သမား၊ Passport၊ Host ဖြင့် ရှာရန်...',
  'invoices.filterAllBalances': 'လက်ကျန် အားလုံး',
  'invoices.filterHasRemain': 'ကျန်ငွေရှိသူများ',
  'invoices.filterFullyPaid': 'ပေးပြီးသူများ',
  'invoices.emptyWorkers': 'ဤ Fee Type အတွက် အလုပ်သမား မှတ်တမ်း မရှိပါ။',
  'invoices.emptyHosts': 'ဤ Fee Type အတွက် Host Company မှတ်တမ်း မရှိပါ။',
  'invoices.searchHost': 'Host Company၊ Supervising Org ဖြင့် ရှာရန်...',
  'invoices.hostInvoiceHint': 'အရင် Supervising Org ရွေးပါ၊ ပြီးမှ Host Company ရွေးပါ။ ထို Host အောက်ရှိ အလုပ်သမားအားလုံးအတွက် Invoice တစ်စောင် ထုတ်ပါမည်။',
  'invoices.hostWorkers': 'Host အောက်ရှိ အလုပ်သမားများ',
  'invoices.hostWorkersEmpty': 'ဤ Host တွင် အလုပ်သမား မရှိသေးပါ။',
  'invoices.hostInvoiceAmountHint': 'စုစုပေါင်းငွေသည် ရွေးထားသော Host အောက်ရှိ အလုပ်သမားများ၏ Fee ပေါင်းဖြစ်သည်။',
  'invoices.workerCount': 'အလုပ်သမား အရေအတွက်',
  'invoices.openDetail': 'အသေးစိတ် ဖွင့်ရန်',
  'invoices.colHost': 'Host Company',
  'invoices.feeType': 'Fee Type',
  'invoices.createTitle': 'Invoice အသစ် ထုတ်ပေးရန်',
  'invoices.editTitle': 'Invoice အချက်အလက် ပြင်ဆင်ရန်',
  'invoices.createHint': 'ငွေပေးချေမှုကို Pay ခလုတ်ဖြင့် သီးခြား မှတ်ပါ',
  'invoices.selectWorker': 'အလုပ်သမား ရွေးချယ်ပါ',
  'invoices.invoiceNo': 'Invoice နံပါတ်',
  'invoices.billingPeriod': 'Billing Period',
  'invoices.invoiceDate': 'Invoice Date',
  'invoices.amountSection': 'ကျသင့်ငွေ',
  'invoices.amountHint': 'ဤနေရာတွင် Invoice စုစုပေါင်းသာ သတ်မှတ်ပါ။ ပေးချေမှုကို Pay မှ မှတ်ပါ။',
  'invoices.currency': 'ငွေကြေး',
  'invoices.receiptSentDate': 'Receipt ပို့သည့်နေ့',
  'invoices.createSubmit': 'Invoice ထုတ်မည်',
  'invoices.pay': 'Pay',
  'invoices.payTitle': 'ငွေပေးချေမှု မှတ်ရန်',
  'invoices.payAmount': 'ပေးချေငွေ',
  'invoices.payDate': 'ပေးသည့်နေ့',
  'invoices.paySubmit': 'ပေးချေမည်',
  'invoices.invoicesSection': 'Invoices',
  'invoices.vouchersSection': 'Payment Vouchers',
  'invoices.noInvoicesForWorker': 'ဤအလုပ်သမားအတွက် Invoice မရှိသေးပါ။',
  'invoices.noInvoicesForHost': 'ဤ Host Company အတွက် Invoice မရှိသေးပါ။',
  'invoices.noVouchers': 'ပေးချေမှု voucher မရှိသေးပါ။',
  'invoices.voucherTitle': 'Payment Voucher',
  'invoices.viewVoucher': 'Voucher ကြည့်ရန်',
  'invoices.voucherPreview': 'Voucher Print Preview',
  'invoices.print': 'Print',
  'invoices.back': 'နောက်သို့',
  'invoices.viewSummaryVoucher': 'Total Paid Voucher',
  'invoices.summaryVoucherPreview': 'Summary Voucher Preview',
  'invoices.summaryVoucherTitle': 'Total Payment Summary',
  'invoices.paymentsOnVoucher': 'Payment count',
  'common.view': 'ကြည့်ရန်',

  'dashboard.title': 'စီမံခန့်ခွဲမှု အနှစ်ချုပ်',
  'dashboard.subtitle': 'အေဂျင်စီ အခြေအနေနှင့် ငွေစာရင်း စောင့်ကြည့်မှု (TITP နှင့် SSW)',
  'dashboard.live': 'အသက်ဝင်နေသော စနစ်',
  'dashboard.urgentTitle': 'အရေးပေါ် ငွေတောင်းခံလွှာ သတိပေးချက်',
  'dashboard.urgentDesc': 'ရှေ့ ၇ ရက်အတွင်း ပေးရန်ရှိသော ငွေတောင်းခံလွှာများ',
  'dashboard.expiryTitle': 'စာချုပ် သက်တမ်း ကုန်ဆုံးမည့် သတိပေးချက်',
  'dashboard.expiryDesc': 'ရှေ့ ၆၀ ရက်အတွင်း စာချုပ် သက်တမ်း ကုန်ဆုံးမည့် အလုပ်သမားများ',
  'dashboard.totalWorkers': 'အလုပ်သမား စုစုပေါင်း',
  'dashboard.active': 'အလုပ်လုပ်ဆဲ',
  'dashboard.ended': 'စာချုပ်ပြည့်',
  'dashboard.abscondRate': 'ထွက်ပြေးမှု နှုန်း',
  'dashboard.workersTotal': 'အလုပ်သမား စုစုပေါင်း',
  'dashboard.outstanding': 'ကျန်ရှိငွေ',
  'dashboard.invoicesDue': 'ပေးရန်ရှိ ငွေတောင်းခံလွှာ',
  'dashboard.unsentReceipts': 'မပို့ရသေးသော ပြေစာ',
  'dashboard.pending': 'ဆိုင်းငံ့',
  'dashboard.statusRatio': 'အလုပ်သမား အခြေအနေ အချိုး',
  'dashboard.byVisa': 'ဗီဇာအလိုက် အလုပ်သမား အရေအတွက်',
  'dashboard.recentInvoices': 'နောက်ဆုံး ငွေတောင်းခံလွှာများ',
  'dashboard.recentWorkers': 'နောက်ဆုံး စာရင်းသွင်းထားသော အလုပ်သမားများ',
  'dashboard.workersCount': 'အလုပ်သမား',

  'reports.title': 'စီမံခန့်ခွဲမှု အစီရင်ခံစာများ',
  'reports.subtitle': 'လာမည့် ငွေတောင်းခံလွှာများ၊ ကျန်ရှိငွေများနှင့် စာချုပ် သက်တမ်း ကုန်ဆုံးမှုများ',
  'reports.refresh': 'ဒေတာ ပြန်လည်ရယူရန်',
  'reports.loading': 'အစီရင်ခံစာများ ပြုစုနေပါသည်...',
  'reports.tabUpcoming': 'Upcoming Invoice (ရှေ့ ၁ လ)',
  'reports.tabOutstanding': 'Outstanding Balance (ကျန်ရှိငွေ)',
  'reports.tabFees': 'Fee Payments (Management / Flight / Training)',
  'reports.tabStudents': 'Student Introduction Fees',
  'reports.tabExpiry': 'Contract Expiry (စာချုပ်ပြီးဆုံးမှု)',
  'reports.studentsTitle': 'ကျောင်းသား မိတ်ဆက်ကြေး အစီရင်ခံစာ',
  'reports.studentsDesc': 'ကျောင်းသား တစ်ဦးချင်း၏ မိတ်ဆက်ကြေး ကျသင့် / ပေးပြီး / ကျန်ငွေ',
  'reports.studentsEmpty': 'ကျောင်းသား မိတ်ဆက်ကြေး မှတ်တမ်း မရှိပါ။',
  'reports.studentsSearch': 'အမည်၊ စဉ်၊ Passport၊ Host ဖြင့် ရှာရန်...',
  'reports.dateFrom': 'From',
  'reports.dateTo': 'To',
  'reports.clearDates': 'Clear dates',
  'reports.upcomingTitle': 'ရှေ့လာမည့် ၁ လအတွင်း Invoice ထုတ်ရန် ကျရောက်နေသော စာရင်း',
  'reports.upcomingDesc':
    'အလုပ်သမား နှင့် Host Company အလိုက် ထုတ်ရမည့် ရက်စွဲ အချိန်မီ သတိပေးချက်',
  'reports.upcomingEmpty': 'ရှေ့ ၁ လအတွင်း Invoice ထုတ်ရန် ကျရောက်သော စာရင်း မရှိပါ။',
  'reports.upcomingTableTitle': 'Upcoming Invoice Report',
  'reports.outstandingTitle': 'Invoice ကျန်ရှိငွေ နှင့် Receipt ပို့ရန် ကျန်ရှိသော စာရင်း',
  'reports.outstandingDesc': 'Fee Type အလိုက် Invoice လက်ခံ/ကျန်ငွေ စစ်ဆေးရန်',
  'reports.outstandingEmpty':
    'ကျန်ရှိငွေ သို့မဟုတ် Receipt ပို့ရန် ကျန်ရှိသော မှတ်တမ်း မရှိပါ။',
  'reports.outstandingTableTitle': 'Outstanding Balance Report',
  'reports.feesTitle': 'Management / Flight / Training Fee ပေးချေမှု အစီရင်ခံစာ',
  'reports.feesDesc':
    'Worker တွင် သတ်မှတ်ထားသော Fee Amount နှင့် Invoice (Fee Type) မှ လက်ခံငွေကို နှိုင်းယှဉ်ပြသည်။ အပေါ်က ကတ်ကို နှိပ်၍ Fee အမျိုးအစား စစ်ထုတ်နိုင်သည်။',
  'reports.feesEmpty': 'စစ်ထုတ်မှုနှင့် ကိုက်ညီသော Fee မှတ်တမ်း မရှိပါ။',
  'reports.feesTableTitle': 'Fee Payment Report',
  'reports.feeFilterOutstanding': 'ကျန်ငွေရှိသူများသာ',
  'reports.feeFilterAll': 'အားလုံး',
  'reports.feeSearch': 'အမည်၊ စဉ်၊ Passport၊ Host ဖြင့် ရှာရန်...',
  'reports.feeTypeAll': 'Fee အားလုံး',
  'reports.expiryTitle': 'စာချုပ်သက်တမ်း ကုန်တော့မည့် အလုပ်သမားများ စာရင်း',
  'reports.expiryDesc': 'စာချုပ်ပြီးဆုံးမည့် ရက်စွဲအလိုက် စီစဉ်ထားသော သတိပေး စာရင်း',
  'reports.expiryEmpty': 'စာချုပ်သက်တမ်း မှတ်တမ်း မရှိပါ။',
  'reports.expiryTableTitle': 'Contract Expiry Timeline',
  'reports.records': '{count} Records',
  'reports.days': '{count} ရက်',
  'reports.print': 'Print',
  'reports.date': 'Date',
  'reports.notAvailable': 'N/A',
  'reports.receiptSent': 'Receipt Sent',
  'reports.receiptPending': 'Receipt Pending',
  'reports.badgeUpcoming': 'UPCOMING',
  'reports.badgeOutstanding': 'OUTSTANDING',
  'reports.badgeContract': 'CONTRACT',
  'reports.badgeFlight': 'FLIGHT',
  'reports.badgeTraining': 'TRAINING',
  'reports.badgeManagement': 'MANAGEMENT',
  'reports.badgeStudents': 'STUDENT',
  'reports.colSerial': 'စဉ်',
  'reports.colWorker': 'အလုပ်သမား',
  'reports.colWorkerSerial': 'စဉ် / အလုပ်သမား',
  'reports.colWorkerName': 'အလုပ်သမားအမည်',
  'reports.colPassport': 'Passport',
  'reports.colHost': 'Host',
  'reports.colHostCompany': 'Host Company',
  'reports.colSupervisingOrg': 'ကြီးကြပ်ရေးအဖွဲ့',
  'reports.colLastInvoice': 'နောက်ဆုံး Invoice',
  'reports.colNextInvoice': 'နောက်တစ်ကြိမ် Invoice',
  'reports.colDaysRemaining': 'ကျန်ရက်',
  'reports.colAmountDue': 'ကျသင့်ကြေး',
  'reports.colInvoiceNo': 'Invoice No',
  'reports.colTotal': 'စုစုပေါင်း',
  'reports.colReceived': 'လက်ခံရရှိ',
  'reports.colOutstanding': 'ကျန်ရှိငွေ',
  'reports.colReceiptNo': 'Receipt No',
  'reports.colPaymentDate': 'ငွေဝင်သည့်နေ့',
  'reports.colReceiptStatus': 'Receipt Status',
  'reports.colFeeType': 'Fee Type',
  'reports.colInstallments': 'အရစ်ကျ',
  'reports.colInvoicesInstallments': 'Invoices / Installments',
  'reports.colLastPayment': 'နောက်ဆုံးပေးသည့်နေ့',
  'reports.colStatus': 'အခြေအနေ',
  'reports.colReceiptPayment': 'Receipt / ငွေဝင်နေ့',
  'reports.colVisaType': 'Visa Type',
  'reports.colDepartureDate': 'ထွက်ခွာသည့်နေ့',
  'reports.colContractEndDate': 'စာချုပ်ပြီးဆုံးမည့်နေ့',
  'reports.colDaysToExpiry': 'ကျန်ရှိရက်',
  'reports.voucherUpcoming': 'Upcoming Invoice Voucher',
  'reports.voucherUpcomingSubtitle': 'Management Fee — next billing reminder',
  'reports.voucherOutstanding': 'Outstanding Balance Voucher',
  'reports.voucherExpiry': 'Contract Expiry Voucher',
  'reports.voucherSuffix': 'Voucher',
  'reports.voucherAmountDue': 'Amount Due',
  'reports.voucherBalanceDue': 'Balance Due',
  'reports.voucherDue': 'Due',
  'reports.voucherPaid': 'Paid',

  'settings.title': 'စနစ် ဆက်တင်များ',
  'settings.subtitle': 'ပုံနှိပ် voucher နှင့် ဒေတာထည့်သွင်းမှု dropdown များအတွက် ဘုံသတ်မှတ်ချက်များ',
  'settings.usersTab': 'အသုံးပြုသူ အကောင့်များ',

  'users.title': 'အသုံးပြုသူ အကောင့် စီမံခြင်း',
  'users.subtitle': 'အကောင့်ဖန်တီးခြင်းနှင့် Function Permission (CRUD) ထိန်းချုပ်ခြင်း',
  'users.add': 'အကောင့်အသစ်',
  'users.edit': 'အကောင့် ပြင်ဆင်ရန်',
  'users.colName': 'အမည်',
  'users.colEmail': 'အီးမေးလ်',
  'users.colRole': 'Role',
  'users.password': 'စကားဝှက်',
  'users.passwordHint': '(ဗလာထားရင် မပြောင်းပါ)',
  'users.passwordRequired': 'အကောင့်အသစ်အတွက် စကားဝှက် လိုအပ်သည်',
  'users.titleField': 'ရာထူး / ခေါင်းစဉ်',
  'users.active': 'Active',
  'users.inactive': 'Inactive',
  'users.permissions': 'Function Permissions (CRUD)',
  'users.permissionsHint': 'Role ရွေးသည့်အခါ default permissions တင်မည်။ လိုအပ်သလို checkbox ဖြင့် ပြင်နိုင်သည်။',
  'users.module': 'Module',
  'users.all': 'အားလုံး',
  'users.toggle': 'Toggle',
  'users.empty': 'အသုံးပြုသူ မရှိသေးပါ',
  'users.search': 'အမည်၊ အီးမေးလ်၊ အခန်းကဏ္ဍ ရှာရန်...',
  'users.noAccess': 'User Accounts ကို ကြည့်ခွင့် မရှိပါ',
  'users.loadFail': 'အသုံးပြုသူစာရင်း မရယူနိုင်ပါ',
  'users.required': 'အမည်နှင့် အီးမေးလ် လိုအပ်သည်',
  'users.saved': 'အကောင့် သိမ်းဆည်းပြီးပါပြီ',
  'users.saveFail': 'သိမ်းဆည်းမှု မအောင်မြင်ပါ',
  'users.deleted': 'အကောင့် ဖျက်ပြီးပါပြီ',
  'users.deleteFail': 'ဖျက်၍ မရပါ',
  'users.deleteConfirm': 'ဤအကောင့်ကို ဖျက်မည်မှာ သေချာပါသလား?',
  'users.denied': 'ဤလုပ်ဆောင်ချက်အတွက် ခွင့်ပြုချက် မရှိပါ',

  'perm.module.dashboard': 'Dashboard',
  'perm.module.workers': 'Workers',
  'perm.module.students': 'Students',
  'perm.module.deployments': 'Deployments',
  'perm.module.invoices': 'Invoices',
  'perm.module.reports': 'Reports',
  'perm.module.settings': 'Settings',
  'perm.module.users': 'User Accounts',
  'perm.action.create': 'Create',
  'perm.action.read': 'Read',
  'perm.action.update': 'Update',
  'perm.action.delete': 'Delete',
  'settings.printTab': 'ပုံနှိပ် ဆက်တင်',
  'settings.variablesTab': 'စနစ် ကိန်းရှင်များ',
  'settings.currencyTab': 'ငွေလဲနှုန်း',
  'settings.currencyHint': 'Japan (JPY) နှင့် Myanmar (MMK) လဲလှယ်နှုန်း သတ်မှတ်ပြီး စနစ်တစ်ခုလုံးတွင် ပြသမည့် ငွေကြေးကို ရွေးပါ။ Fee / Invoice များကို JPY အဖြစ် သိမ်းပြီး Display ကို MMK ပြောင်းပါက နှုန်းအတိုင်း ပြောင်းပြသည်။',
  'settings.exchangeRate': 'လဲလှယ်နှုန်း (၁ JPY = ? MMK)',
  'settings.exchangeRateHint': 'ဥပမာ — ၁ ယန် = ၂၀ ကျပ် ဆိုပါက ၂၀ ထည့်ပါ။',
  'settings.displayCurrency': 'ပြသမည့် ငွေကြေး',
  'settings.displayJpy': 'Japan Currency (¥ / JPY)',
  'settings.displayMmk': 'Myanmar Currency (Ks / MMK)',
  'settings.currencyPreview': 'နမူနာ ပြောင်းလဲမှု',
  'settings.currencyPreviewExample': 'Flight Fee {jpy} → {mmk}',
  'settings.saveCurrency': 'ငွေလဲနှုန်း သိမ်းမည်',
  'settings.currencySaved': 'ငွေလဲနှုန်း သိမ်းပြီးပါပြီ။',
  'settings.currencySaveFail': 'ငွေလဲနှုန်း သိမ်း၍ မရပါ။',
  'settings.rateInvalid': 'လဲလှယ်နှုန်းသည် ၀ ထက်ကြီးရမည်။',
  'nav.currency': 'ငွေကြေး',
  'nav.theme': 'အလင်းအမှောင်',
  'nav.themeSystem': 'စနစ်အတိုင်း',
  'nav.themeLight': 'အလင်း',
  'nav.themeDark': 'အမှောင်',
  'nav.language': 'ဘာသာစကား',
  'settings.printHint': 'ငွေတောင်းခံလွှာ / voucher ပေါ်တွင် ပြမည့် အေဂျင်စီ လိုဂို၊ အမည်၊ လိပ်စာ၊ ဖုန်း',
  'settings.printHintDual': 'ငွေချေပြီး voucher နှစ်မျိုး (Voucher 1 / Voucher 2) အတွက် အေဂျင်စီ အချက်အလက် သီးခြား သတ်မှတ်ပါ။',
  'settings.voucherSlot1': 'Voucher 1',
  'settings.voucherSlot2': 'Voucher 2',
  'settings.logo': 'လိုဂို',
  'settings.uploadLogo': 'လိုဂို ရွေးရန်',
  'settings.removeLogo': 'လိုဂို ဖယ်ရှားရန်',
  'settings.agencyName': 'အေဂျင်စီ အမည်',
  'settings.address': 'လိပ်စာ',
  'settings.phone': 'ဖုန်းနံပါတ်',
  'settings.savePrint': 'ပုံနှိပ် ဆက်တင် သိမ်းမည်',
  'settings.variablesHint': 'ဤနေရာတွင် သတ်မှတ်ထားသော တန်ဖိုးများကို အလုပ်သမား ထည့်သည့်အခါ dropdown ဖြင့်သာ ရွေးရမည်။',
  'settings.addVariable': 'ထည့်မည်',
  'settings.addVariablePlaceholder': 'တန်ဖိုး အသစ် ရိုက်ထည့်ပါ...',
  'settings.catVisa': 'ဗီဇာ အမျိုးအစား',
  'settings.catOrg': 'ကြီးကြပ်ရေးအဖွဲ့',
  'settings.catHost': 'လက်ခံ ကုမ္ပဏီ',
  'settings.catJob': 'အလုပ်အမျိုးအစား',
  'settings.catSchool': 'ကျောင်းအမည်',
  'settings.selectOrg': 'ကြီးကြပ်ရေးအဖွဲ့ ရွေးပါ',
  'settings.hostNeedsOrg': 'Host Company ထည့်ရန် Supervising Org ကို အရင် ရွေးပါ။',
  'settings.printSaved': 'ပုံနှိပ် ဆက်တင် သိမ်းပြီးပါပြီ။',
  'settings.printSaveFail': 'သိမ်းဆည်း၍ မရပါ။',
  'settings.varAdded': 'ကိန်းရှင် ထည့်ပြီးပါပြီ။',
  'settings.varAddFail': 'ထည့်၍ မရပါ။',
  'settings.logoTooBig': 'လိုဂိုသည် ၂MB အောက် ဖြစ်ရမည်။',
  'settings.loadFail': 'ဆက်တင်များ ရယူ၍ မရပါ။',

  'status.active': 'အလုပ်လုပ်ဆဲ',
  'status.ended': 'စာချုပ်ပြည့်',
  'status.absconded': 'ထွက်ပြေး',
  'status.pending': 'ဆိုင်းငံ့',
  'status.partial': 'တစ်စိတ်တစ်ပိုင်း',
  'status.paid': 'ပေးပြီး',
  'status.overdue': 'ရက်လွန်',
};

const EN: Dict = {
  'nav.dashboard': 'Dashboard',
  'nav.workers': 'Workers',
  'nav.students': 'Students',
  'nav.deployments': 'Deployments',
  'nav.invoices': 'Invoices',
  'nav.reports': 'Reports',
  'nav.settings': 'Settings',
  'nav.menu': 'Navigation Menu',
  'nav.systemStatus': 'System Status',
  'nav.logout': 'Log out',
  'nav.notifications': 'Notifications',
  'nav.tagline': 'Overseas Employment Agency & Automated Billing',

  'alert.title': 'Active Alert Center',
  'alert.subtitle': 'Review upcoming invoice due dates and contracts nearing expiry',
  'alert.urgentInvoices': 'Invoices due within 7 days',
  'alert.expiring': 'Contracts expiring soon',
  'alert.none': 'No alerts',
  'alert.countInvoices': '',
  'alert.countWorkers': '',
  'alert.filterAll': 'All',
  'alert.totalBadge': 'alerts',
  'alert.colType': 'Type',
  'alert.colSubject': 'Name / Ref',
  'alert.colDetail': 'Host Company',
  'alert.colDate': 'Date',
  'alert.goInvoices': 'Go to Invoices',
  'alert.goDeployments': 'Go to Deployments',
  'alert.markAllRead': 'Mark all as read',
  'alert.unreadBadge': 'unread',
  'alert.enableBrowser': 'Enable browser notifications',
  'alert.browserOn': 'Browser notifications on',
  'alert.browserDenied': 'Blocked in browser settings',
  'alert.browserUnsupported': 'This browser does not support notifications.',
  'alert.testPush': 'Send test push',
  'alert.vapidMissing': 'Add VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY to backend/.env',
  'alert.pushReady': 'Web Push connected.',
  'alert.pushError': 'Could not connect Web Push. Check permission and VAPID keys.',

  'common.loading': 'Loading system data...',
  'common.search': 'Search...',
  'common.allStatuses': 'All Statuses',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.select': '— Select —',
  'common.male': 'Male',
  'common.female': 'Female',
  'common.noData': 'No records found',
  'common.online': 'Online',
  'common.showFilters': 'Show search / filters',
  'common.hideFilters': 'Hide search / filters',

  'print.copy': 'Copy',
  'print.copySuccess': 'Copied to clipboard',
  'print.copySuccessHint': 'Paste into chat / messenger to send as a photo.',
  'print.shareSuccess': 'Shared successfully',
  'print.downloadSuccess': 'Image downloaded',
  'print.downloadSuccessHint': 'Send the downloaded file in chat.',
  'print.copyFail': 'Could not copy',

  'export.excel': 'Excel Export',
  'export.pdf': 'PDF Download',

  'pagination.rowsPerPage': 'Rows per page',
  'pagination.showing': 'Showing',
  'pagination.of': 'of',
  'pagination.previous': 'Previous',
  'pagination.next': 'Next',
  'pagination.page': 'Page',

  'login.title': 'User Login',
  'login.welcome': 'Sign in with your account to continue.',
  'login.heroLine': 'Overseas employment operations, billing & contracts — one workspace.',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.remember': 'Remember me',
  'login.submit': 'Login',
  'login.loggingIn': 'Logging in…',
  'login.needFields': 'Please enter your email and password.',
  'login.invalid': 'Invalid email or password',
  'login.failed': 'Login failed. Please try again.',
  'login.serverError': 'Unable to reach the server. Please try again.',
  'login.showPassword': 'Show password',
  'login.hidePassword': 'Hide password',

  'workers.title': 'Worker Profile Management',
  'students.title': 'Student Profile Management',
  'students.subtitle': 'Introduction fee, payments and vouchers',
  'students.add': 'Add student',
  'students.search': 'Search by name, serial, passport, school...',
  'students.empty': 'No student records found.',
  'students.createTitle': 'Register new student',
  'students.editTitle': 'Edit student',
  'students.createHint': 'Set introduction fee only. Record payments on the Fees page.',
  'students.editHint': 'Update student profile and introduction fee',
  'students.sectionProfile': '1. Student profile',
  'students.sectionDeployment': '2. Visa & school details',
  'students.sectionFinancial': '3. Introduction fee',
  'students.financialHint': 'Set Introduction Fee in JPY. Record payments/vouchers under Introduction Fees.',
  'students.introductionFee': 'Introduction Fee',
  'students.incompleteTitle': 'Incomplete information',
  'students.nameRequired': 'Please enter the student name.',
  'students.dropdownRequired': 'Enter Visa / School Name / School Address.',
  'students.fieldsRequired': 'Enter Visa / School Name / School Address.',
  'students.visaHint': 'Select visa type and school name from Settings → System Variables.',
  'students.schoolInvoiceHint': 'Select a School Name to invoice the combined Introduction Fees of its students.',
  'students.schoolInvoiceAmountHint': 'Amount defaults to the sum of students’ Introduction Fees (editable).',
  'students.schoolStudents': 'Students under this school',
  'students.schoolStudentsEmpty': 'No students found under this School Name yet.',
  'students.studentCount': 'Students',
  'students.searchSchool': 'Search by school name...',
  'students.schoolName': 'School Name',
  'students.schoolAddress': 'School Address',
  'students.colSchool': 'School Name / Address',
  'students.openFees': 'Introduction Fee',
  'students.profilesTab': 'Profiles',
  'students.feesTab': 'Introduction Fees',
  'students.feesTitle': 'Student introduction fee management',
  'students.feesSubtitle': 'Create invoices, record payments and vouchers',
  'students.feesEmpty': 'No introduction fee records yet.',
  'students.deleteTitle': 'Delete student?',
  'students.deleteSimple': 'This will permanently delete student ({name}) from the system.',
  'students.deleteRelatedTitle': 'Related student invoices found',
  'students.deleteRelatedText': '{name} ({serial}) has {count} related student invoice record(s). Hard delete will remove those related records too.',
  'students.deleteRelatedList': 'Related student invoices',
  'students.deleteConfirmSimple': 'Delete',
  'students.deleteConfirmHard': 'Hard Delete',
  'students.deleteCancel': 'Cancel',
  'students.deleted': 'Student deleted',
  'students.deletedWithRelated': 'Student and {count} related invoice(s) deleted',
  'students.deleteFail': 'Could not delete student',
  'students.deleteLoadFail': 'Could not check related student records',
  'students.deleteInvoiceTitle': 'Delete student invoice?',
  'students.deleteInvoiceText': 'This will permanently delete the selected student introduction invoice.',
  'students.deleteInvoiceSuccess': 'Student invoice deleted',
  'students.deleteInvoiceFail': 'Could not delete student invoice',
  'students.invoiceHint': 'Record payments separately with the Pay button',
  'deployments.title': 'Visa / Contract Management',
  'deployments.subtitle': 'Visa, host company, departure / Japan entry and contract end dates',
  'workers.subtitle': 'Personal profiles, status (Active / Absconded / Ended) and notes',
  'workers.add': 'Add New Worker',
  'workers.template': 'Excel Template',
  'workers.import': 'Excel Import',
  'workers.importSuccess': 'Imported {count} worker(s) from Excel',
  'workers.importFailTitle': 'Excel Import failed',
  'workers.importFailHint': 'No data was inserted — validation failed and the import was rolled back.',
  'workers.importing': 'Importing...',
  'workers.search': 'Search by name, serial, passport, notes...',
  'deployments.search': 'Search by name, passport, host company, visa...',
  'workers.allVisas': 'All Visa Types',
  'workers.colName': 'ID / Name',
  'workers.colPassport': 'Passport / DOB',
  'workers.colVisa': 'Visa / Job Type',
  'workers.colCompany': 'Supervising Org / Host Company',
  'workers.colHostBrief': 'Host Company',
  'workers.colContract': 'Contract End Date',
  'workers.departure': 'Departure',
  'workers.empty': 'No workers match your search.',
  'deployments.empty': 'No deployment records match your filters.',
  'deployments.colVisa': 'Visa / Job Type',
  'deployments.colCompany': 'Host / Supervising Org',
  'deployments.colOwnCard': 'Own Card',
  'deployments.colDeparture': 'Departure',
  'deployments.colJapanEntry': 'Japan Entry',
  'deployments.colContract': 'Contract End',
  'deployments.allExpiry': 'All contract windows',
  'deployments.expiry30': 'Ending within 30 days',
  'deployments.expiry90': 'Ending within 90 days',
  'deployments.expiryPast': 'Already expired',
  'deployments.expiryNone': 'No end date set',
  'deployments.daysLeft': '{days} days left',
  'deployments.expiredDays': '{days} days overdue',
  'workers.dateLabel': 'Date',
  'workers.abscondedTitle': 'Mark Worker as Absconded',
  'workers.abscondedConfirm': 'Confirm Absconded',
  'workers.abscondedDate': 'Absconded Date',
  'workers.notes': 'Notes',
  'workers.deleteTitle': 'Delete worker?',
  'workers.deleteSimple': 'This will permanently delete worker ({name}) from the system.',
  'workers.deleteRelatedTitle': 'Related reports / invoices found',
  'workers.deleteRelatedText': '{name} ({serial}) has {count} related invoice/report record(s). Hard delete will also remove those related records.',
  'workers.deleteRelatedList': 'Related invoices',
  'workers.deleteConfirmSimple': 'Delete',
  'workers.deleteConfirmHard': 'Hard Delete (incl. related)',
  'workers.deleteCancel': 'Cancel',
  'workers.deleted': 'Worker deleted',
  'workers.deletedWithRelated': 'Worker and {count} related invoice(s) deleted',
  'workers.deleteFail': 'Could not delete',
  'workers.deleteLoadFail': 'Could not check related records',

  'workerModal.addTitle': 'Register New Worker',
  'workerModal.editTitle': 'Edit Worker Profile',
  'workerModal.createHint': 'Enter the new worker profile, visa, and fee settings.',
  'workerModal.editHint': 'Update the worker profile and save your changes.',
  'workerModal.incompleteTitle': 'Incomplete information',
  'workerModal.financialHint':
    'This section only defines fee amounts. Manage payment history from the Invoices page.',
  'workerModal.section1': '1. Worker Profile',
  'workerModal.section2': '2. Deployment & Contract',
  'workerModal.section3': '3. Financial Configuration',
  'workerModal.serial': 'Serial No',
  'workerModal.name': 'Full Name *',
  'workerModal.gender': 'Gender',
  'workerModal.dob': 'Date of Birth',
  'workerModal.passport': 'Passport No *',
  'workerModal.status': 'Status',
  'workerModal.abscondedDate': 'Absconded Date',
  'workerModal.visa': 'Visa Type *',
  'workerModal.org': 'Supervising Org *',
  'workerModal.host': 'Host Company *',
  'workerModal.job': 'Job Category *',
  'workerModal.ownCard': 'Own Card Date',
  'workerModal.departure': 'Departure Date',
  'workerModal.entry': 'Japan Entry Date',
  'workerModal.contractEnd': 'Contract End Date',
  'workerModal.dropdownHint': 'Select Visa / Org / Company / Job from Settings → System Variables.',
  'workerModal.nameRequired': 'Please enter the worker name.',
  'workerModal.dropdownRequired': 'Please select Visa / Supervising Org / Host Company / Job Category.',
  'workerModal.flightFee': 'Flight Fee',
  'workerModal.trainingFee': 'Training Fee',
  'workerModal.managementFee': 'Management Fee',
  'workerModal.billingCycle': 'Billing Cycle (Months)',
  'workerModal.notes': 'Notes',

  'workerDetail.edit': 'Edit',
  'workerDetail.currentStatus': 'Current Status',
  'workerDetail.personalInfo': 'Personal Info',
  'workerDetail.deploymentInfo': 'Visa & Deployment Details',
  'workerDetail.financialInfo': 'Financial Configuration',
  'workerDetail.financialHint':
    'This section only defines fee amounts. Manage payment history from the Invoices page.',
  'workerDetail.invoicesTitle': 'Invoice & Payment History ({count})',
  'workerDetail.noInvoices': 'No invoices have been created for this worker yet.',
  'workerDetail.passport': 'Passport',
  'workerDetail.dob': 'DOB',
  'workerDetail.close': 'Close',
  'workerDetail.abscondedDate': 'Absconded Date',
  'workerDetail.billingCycle': 'Cycle: {months} months',
  'workerDetail.notAvailable': 'N/A',
  'workerDetail.notesTitle': 'Notes',

  'invoices.title': 'Invoice & Payment Tracker',
  'invoices.subtitle': 'Management fee invoices, received amounts, receipts and outstanding balances',
  'invoices.add': 'Create Invoice',
  'invoices.search': 'Search by invoice no, worker, host company, receipt no...',
  'invoices.colInvoice': 'Invoice No / Period',
  'invoices.colWorker': 'Worker / Company',
  'invoices.colDates': 'Last / Next Invoice Date',
  'invoices.colAmount': 'Total / Received / Outstanding',
  'invoices.colReceipt': 'Receipt Record',
  'invoices.empty': 'No invoices found matching your filters.',
  'invoices.detailTitle': 'Invoice details',
  'invoices.last': 'Last',
  'invoices.next': 'Next',
  'invoices.total': 'Total',
  'invoices.received': 'Received',
  'invoices.outstanding': 'Outstanding',
  'invoices.totalAmount': 'Total Amount',
  'invoices.totalPaid': 'Total Paid',
  'invoices.remainAmount': 'Remain Amount',
  'invoices.invoiceCount': 'Invoices',
  'invoices.searchWorker': 'Search worker, passport, host...',
  'invoices.filterAllBalances': 'All balances',
  'invoices.filterHasRemain': 'Has remaining',
  'invoices.filterFullyPaid': 'Fully paid',
  'invoices.emptyWorkers': 'No workers found for this fee type.',
  'invoices.emptyHosts': 'No host companies found for this fee type.',
  'invoices.searchHost': 'Search host company or supervising org...',
  'invoices.hostInvoiceHint': 'Select a Supervising Org first, then a Host Company. One invoice covers all workers under that host.',
  'invoices.hostWorkers': 'Workers under this host',
  'invoices.hostWorkersEmpty': 'No workers under this host yet.',
  'invoices.hostInvoiceAmountHint': 'Total is the sum of fees for workers under the selected host.',
  'invoices.workerCount': 'Workers',
  'invoices.openDetail': 'Open details',
  'invoices.colHost': 'Host Company',
  'invoices.feeType': 'Fee Type',
  'invoices.createTitle': 'Create Invoice',
  'invoices.editTitle': 'Edit Invoice',
  'invoices.createHint': 'Record payments separately with the Pay button',
  'invoices.selectWorker': 'Select worker',
  'invoices.invoiceNo': 'Invoice No',
  'invoices.billingPeriod': 'Billing Period',
  'invoices.invoiceDate': 'Invoice Date',
  'invoices.amountSection': 'Invoice Amount',
  'invoices.amountHint': 'Set the invoice total here. Use Pay to record payments.',
  'invoices.currency': 'Currency',
  'invoices.receiptSentDate': 'Receipt sent date',
  'invoices.createSubmit': 'Create Invoice',
  'invoices.pay': 'Pay',
  'invoices.payTitle': 'Record Payment',
  'invoices.payAmount': 'Payment amount',
  'invoices.payDate': 'Payment date',
  'invoices.paySubmit': 'Pay',
  'invoices.invoicesSection': 'Invoices',
  'invoices.vouchersSection': 'Payment Vouchers',
  'invoices.noInvoicesForWorker': 'No invoices yet for this worker.',
  'invoices.noInvoicesForHost': 'No invoices yet for this host company.',
  'invoices.noVouchers': 'No payment vouchers yet.',
  'invoices.voucherTitle': 'Payment Voucher',
  'invoices.viewVoucher': 'View voucher',
  'invoices.voucherPreview': 'Voucher Print Preview',
  'invoices.print': 'Print',
  'invoices.back': 'Back',
  'invoices.viewSummaryVoucher': 'Total Paid Voucher',
  'invoices.summaryVoucherPreview': 'Summary Voucher Preview',
  'invoices.summaryVoucherTitle': 'Total Payment Summary',
  'invoices.paymentsOnVoucher': 'Payment count',
  'common.view': 'View',

  'dashboard.title': 'Management Overview',
  'dashboard.subtitle': 'Agency status and billing tracking (TITP & SSW)',
  'dashboard.live': 'Live System',
  'dashboard.urgentTitle': 'Urgent Invoices Alert',
  'dashboard.urgentDesc': 'Invoices due within the next 7 days',
  'dashboard.expiryTitle': 'Contract Expiry Alert',
  'dashboard.expiryDesc': 'Contracts ending within the next 60 days',
  'dashboard.totalWorkers': 'Total Workers',
  'dashboard.active': 'Active',
  'dashboard.ended': 'Ended',
  'dashboard.abscondRate': 'Absconding Rate',
  'dashboard.workersTotal': 'Workers Total',
  'dashboard.outstanding': 'Outstanding Balance',
  'dashboard.invoicesDue': 'Invoices Due',
  'dashboard.unsentReceipts': 'Unsent Receipts',
  'dashboard.pending': 'Pending',
  'dashboard.statusRatio': 'Worker Status Ratio',
  'dashboard.byVisa': 'Workers by Visa Type',
  'dashboard.recentInvoices': 'Recent Invoices',
  'dashboard.recentWorkers': 'Recently Registered Workers',
  'dashboard.workersCount': 'Workers',

  'reports.title': 'Management Reports',
  'reports.subtitle': 'Upcoming invoices, outstanding balances and contract expirations',
  'reports.refresh': 'Refresh data',
  'reports.loading': 'Preparing reports...',
  'reports.tabUpcoming': 'Upcoming Invoice (Next 1 Month)',
  'reports.tabOutstanding': 'Outstanding Balance',
  'reports.tabFees': 'Fee Payments (Management / Flight / Training)',
  'reports.tabStudents': 'Student Introduction Fees',
  'reports.tabExpiry': 'Contract Expiry',
  'reports.studentsTitle': 'Student introduction fee report',
  'reports.studentsDesc': 'Per-student introduction fee due / received / outstanding',
  'reports.studentsEmpty': 'No student introduction fee records.',
  'reports.studentsSearch': 'Search by name, serial, passport, host...',
  'reports.dateFrom': 'From',
  'reports.dateTo': 'To',
  'reports.clearDates': 'Clear dates',
  'reports.upcomingTitle': 'Invoices due within the next 1 month',
  'reports.upcomingDesc':
    'Timely reminders by worker and host company for the next invoice issue date.',
  'reports.upcomingEmpty': 'No upcoming invoices are due within the next month.',
  'reports.upcomingTableTitle': 'Upcoming Invoice Report',
  'reports.outstandingTitle': 'Outstanding balances and pending receipts',
  'reports.outstandingDesc':
    'Review received and outstanding amounts by invoice fee type.',
  'reports.outstandingEmpty': 'No outstanding balance or pending receipt records found.',
  'reports.outstandingTableTitle': 'Outstanding Balance Report',
  'reports.feesTitle': 'Management / Flight / Training Fee Payment Report',
  'reports.feesDesc':
    'Compares worker-configured fee amounts with payments recorded on invoices by fee type. Tap a summary card to filter.',
  'reports.feesEmpty': 'No fee records match the current filters.',
  'reports.feesTableTitle': 'Fee Payment Report',
  'reports.feeFilterOutstanding': 'Outstanding only',
  'reports.feeFilterAll': 'All records',
  'reports.feeSearch': 'Search by name, serial, passport, host...',
  'reports.feeTypeAll': 'All fee types',
  'reports.expiryTitle': 'Workers with contracts nearing expiry',
  'reports.expiryDesc': 'Planned reminders organized by contract end date.',
  'reports.expiryEmpty': 'No contract expiry records found.',
  'reports.expiryTableTitle': 'Contract Expiry Timeline',
  'reports.records': '{count} Records',
  'reports.days': '{count} days',
  'reports.print': 'Print',
  'reports.date': 'Date',
  'reports.notAvailable': 'N/A',
  'reports.receiptSent': 'Receipt Sent',
  'reports.receiptPending': 'Receipt Pending',
  'reports.badgeUpcoming': 'UPCOMING',
  'reports.badgeOutstanding': 'OUTSTANDING',
  'reports.badgeContract': 'CONTRACT',
  'reports.badgeFlight': 'FLIGHT',
  'reports.badgeTraining': 'TRAINING',
  'reports.badgeManagement': 'MANAGEMENT',
  'reports.badgeStudents': 'STUDENT',
  'reports.colSerial': 'Serial',
  'reports.colWorker': 'Worker',
  'reports.colWorkerSerial': 'Serial / Worker',
  'reports.colWorkerName': 'Worker Name',
  'reports.colPassport': 'Passport',
  'reports.colHost': 'Host',
  'reports.colHostCompany': 'Host Company',
  'reports.colSupervisingOrg': 'Supervising Org',
  'reports.colLastInvoice': 'Last Invoice',
  'reports.colNextInvoice': 'Next Invoice',
  'reports.colDaysRemaining': 'Days Remaining',
  'reports.colAmountDue': 'Amount Due',
  'reports.colInvoiceNo': 'Invoice No',
  'reports.colTotal': 'Total',
  'reports.colReceived': 'Received',
  'reports.colOutstanding': 'Outstanding',
  'reports.colReceiptNo': 'Receipt No',
  'reports.colPaymentDate': 'Payment Date',
  'reports.colReceiptStatus': 'Receipt Status',
  'reports.colFeeType': 'Fee Type',
  'reports.colInstallments': 'Installments',
  'reports.colInvoicesInstallments': 'Invoices / Installments',
  'reports.colLastPayment': 'Last Payment',
  'reports.colStatus': 'Status',
  'reports.colReceiptPayment': 'Receipt / Payment Date',
  'reports.colVisaType': 'Visa Type',
  'reports.colDepartureDate': 'Departure Date',
  'reports.colContractEndDate': 'Contract End Date',
  'reports.colDaysToExpiry': 'Days to Expiry',
  'reports.voucherUpcoming': 'Upcoming Invoice Voucher',
  'reports.voucherUpcomingSubtitle': 'Management Fee — next billing reminder',
  'reports.voucherOutstanding': 'Outstanding Balance Voucher',
  'reports.voucherExpiry': 'Contract Expiry Voucher',
  'reports.voucherSuffix': 'Voucher',
  'reports.voucherAmountDue': 'Amount Due',
  'reports.voucherBalanceDue': 'Balance Due',
  'reports.voucherDue': 'Due',
  'reports.voucherPaid': 'Paid',

  'settings.title': 'System Settings',
  'settings.subtitle': 'Print voucher branding and shared dropdown values for data entry',
  'settings.usersTab': 'User Accounts',

  'users.title': 'User Account Management',
  'users.subtitle': 'Create accounts and control function permissions (CRUD)',
  'users.add': 'New Account',
  'users.edit': 'Edit Account',
  'users.colName': 'Name',
  'users.colEmail': 'Email',
  'users.colRole': 'Role',
  'users.password': 'Password',
  'users.passwordHint': '(leave blank to keep)',
  'users.passwordRequired': 'Password is required for new accounts',
  'users.titleField': 'Title / Position',
  'users.active': 'Active',
  'users.inactive': 'Inactive',
  'users.permissions': 'Function Permissions (CRUD)',
  'users.permissionsHint': 'Selecting a role loads default permissions. Customize with checkboxes.',
  'users.module': 'Module',
  'users.all': 'All',
  'users.toggle': 'Toggle',
  'users.empty': 'No users yet',
  'users.search': 'Search name, email, role...',
  'users.noAccess': 'You do not have access to User Accounts',
  'users.loadFail': 'Failed to load users',
  'users.required': 'Name and email are required',
  'users.saved': 'Account saved',
  'users.saveFail': 'Save failed',
  'users.deleted': 'Account deleted',
  'users.deleteFail': 'Delete failed',
  'users.deleteConfirm': 'Delete this account?',
  'users.denied': 'You do not have permission for this action',

  'perm.module.dashboard': 'Dashboard',
  'perm.module.workers': 'Workers',
  'perm.module.students': 'Students',
  'perm.module.deployments': 'Deployments',
  'perm.module.invoices': 'Invoices',
  'perm.module.reports': 'Reports',
  'perm.module.settings': 'Settings',
  'perm.module.users': 'User Accounts',
  'perm.action.create': 'Create',
  'perm.action.read': 'Read',
  'perm.action.update': 'Update',
  'perm.action.delete': 'Delete',
  'settings.printTab': 'Print Setting',
  'settings.variablesTab': 'System Variables',
  'settings.currencyTab': 'Currency Exchange',
  'settings.currencyHint': 'Set the Japan (JPY) ↔ Myanmar (MMK) rate and choose which currency to show across the app. Fees/invoices are stored in their source currency; switching display to MMK converts using this rate.',
  'settings.exchangeRate': 'Exchange rate (1 JPY = ? MMK)',
  'settings.exchangeRateHint': 'Example — if 1 yen = 20 kyat, enter 20.',
  'settings.displayCurrency': 'Display currency',
  'settings.displayJpy': 'Japan Currency (¥ / JPY)',
  'settings.displayMmk': 'Myanmar Currency (Ks / MMK)',
  'settings.currencyPreview': 'Conversion preview',
  'settings.currencyPreviewExample': 'Flight Fee {jpy} → {mmk}',
  'settings.saveCurrency': 'Save currency settings',
  'settings.currencySaved': 'Currency settings saved.',
  'settings.currencySaveFail': 'Failed to save currency settings.',
  'settings.rateInvalid': 'Exchange rate must be greater than 0.',
  'nav.currency': 'Currency',
  'nav.theme': 'Theme',
  'nav.themeSystem': 'System',
  'nav.themeLight': 'Light',
  'nav.themeDark': 'Dark',
  'nav.language': 'Language',
  'settings.printHint': 'Agency logo, name, address and phone shown on voucher / invoice print',
  'settings.printHintDual': 'Set two agency letterheads (Voucher 1 / Voucher 2). Both appear after every invoice payment.',
  'settings.voucherSlot1': 'Voucher 1',
  'settings.voucherSlot2': 'Voucher 2',
  'settings.logo': 'Logo',
  'settings.uploadLogo': 'Upload Logo',
  'settings.removeLogo': 'Remove Logo',
  'settings.agencyName': 'Agency Name',
  'settings.address': 'Address',
  'settings.phone': 'Phone No',
  'settings.savePrint': 'Save Print Setting',
  'settings.variablesHint': 'Values defined here appear as dropdowns when adding worker data.',
  'settings.addVariable': 'Add',
  'settings.addVariablePlaceholder': 'Enter a new value...',
  'settings.catVisa': 'Visa Types',
  'settings.catOrg': 'Supervising Orgs',
  'settings.catHost': 'Host Companies',
  'settings.catJob': 'Job Categories',
  'settings.catSchool': 'School Names',
  'settings.selectOrg': 'Select supervising org',
  'settings.hostNeedsOrg': 'Select a Supervising Org before adding a Host Company.',
  'settings.printSaved': 'Print settings saved.',
  'settings.printSaveFail': 'Failed to save print settings.',
  'settings.varAdded': 'Variable added.',
  'settings.varAddFail': 'Failed to add.',
  'settings.logoTooBig': 'Logo must be under 2MB.',
  'settings.loadFail': 'Failed to load settings.',

  'status.active': 'Active',
  'status.ended': 'Contract Ended',
  'status.absconded': 'Absconded',
  'status.pending': 'Pending',
  'status.partial': 'Partial',
  'status.paid': 'Paid',
  'status.overdue': 'Overdue',
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggleLang: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) return template;
  return Object.entries(vars).reduce(
    (out, [k, v]) => out.replaceAll(`{${k}}`, String(v)),
    template
  );
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('agency_os_lang');
    return saved === 'EN' || saved === 'MM' || saved === 'JP' ? saved : 'EN';
  });

  const setLang = useCallback((next: Lang) => {
    setLangState(next);
    localStorage.setItem('agency_os_lang', next);
  }, []);

  const toggleLang = useCallback(() => {
    const order: Lang[] = ['EN', 'MM', 'JP'];
    const idx = order.indexOf(lang);
    setLang(order[(idx + 1) % order.length]);
  }, [lang, setLang]);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const dict = lang === 'EN' ? EN : lang === 'JP' ? JP : MM;
      const raw = dict[key] ?? EN[key] ?? key;
      return interpolate(raw, vars);
    },
    [lang]
  );

  const value = useMemo(
    () => ({ lang, setLang, toggleLang, t }),
    [lang, setLang, toggleLang, t]
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
}
